# Generated by Django 6.0.3 on 2026-03-06 11:11

from django.db import migrations, models


def set_names(apps, schema_editor):
    Profile = apps.get_model('portfolio', 'Profile')
    for p in Profile.objects.all():
        parts = p.full_name.split()
        if len(parts) >= 2:
            p.last_name = parts[-1]
            p.first_name = parts[-2] if len(parts) > 1 else parts[0]
        elif parts:
            p.first_name = parts[0]
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Ex: Océane', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Ex: Konan', max_length=100),
        ),
        migrations.RunPython(set_names),
    ]
